server:
  port: 8086

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/arenamanager?currentSchema=auth
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
        hbm2ddl.create_namespaces: true

jwt:
  secret: 4arenamanager-secret-key-muito-longa-para-garantir-256-bits-de-seguranca
  expiration-ms: 900000        # 15 minutos (access token)
  refresh-expiration-ms: 86400000  # 24 horas (refresh token)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
