spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # Este servidor não se registra nele mesmo
    fetch-registry: false         # Não precisa buscar registros de outros servidores
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0  # Sem delay na inicialização em dev
